# Generated by Django 3.1.6 on 2021-12-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Gmailアドレス')),
                ('pas', models.CharField(max_length=20, verbose_name='パスワード')),
            ],
        ),
    ]
