# Generated by Django 3.1.6 on 2021-12-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
