# Generated by Django 3.1.6 on 2022-01-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailservice', '0002_mails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pas',
        ),
        migrations.AddField(
            model_name='mails',
            name='no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mails',
            name='date',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mails',
            name='domain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mails',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
