# Generated by Django 3.1.6 on 2022-01-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailservice', '0003_auto_20220102_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='now',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mails',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mails',
            name='no',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
